#!/usr/bin/env python3
"""Generate russian-layout twin `map` directives for kitty.

Scans the given kitty config files for `map <combo> <action>` lines,
parses the key-combo (supporting chord syntax via `>`), and emits a
duplicate `map` line with every single-char key translated through the
prometeus→ru mapping.

Modes:
  --check (default)  write ~/.config/kitty/kitty-ru.generated.conf
  --apply            same, plus ensure `include kitty-ru.generated.conf`
                     is present at the end of kitty.conf

Skips lines whose translated form already exists in the sources
(avoids duplicating bindings the user wrote manually).
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

MAP_PATH = Path("~/.config/keymaps/prometeus-ru.json").expanduser()
KITTY_DIR = Path("~/.config/kitty").expanduser()
DEFAULT_SOURCES = ["kitty.conf", "prometeum.conf"]
OUT_NAME = "kitty-ru.generated.conf"

# Kitty built-in defaults not present in any config file.
# These bindings are active but invisible to the generator, so we
# inject Russian twins explicitly.  Keep in sync with kitty's defaults.
KITTY_DEFAULTS: list[tuple[str, str]] = [
    ("kitty_mod+c", "copy_to_clipboard"),
    ("kitty_mod+o", "pass_selection_to_program"),
    ("kitty_mod+q", "close_tab"),
    ("kitty_mod+z", "scroll_to_prompt -1"),
    ("kitty_mod+,", "move_tab_backward"),
    ("kitty_mod+.", "move_tab_forward"),
]

MAP_RE = re.compile(r"^\s*map\s+(\S+)(?:\s+(.+))?\s*$")
MODIFIER_TOKENS = {
    "kitty_mod", "ctrl", "control", "shift", "alt", "opt", "option",
    "cmd", "command", "super", "hyper", "meta",
}


def load_xlate() -> dict[str, str]:
    data = json.loads(MAP_PATH.read_text())
    return {**data["map"], **data["shift_map"]}


def translate_combo(combo: str, xlate: dict[str, str]) -> str | None:
    """Translate a kitty key-combo. Returns translated combo or None
    if nothing was translatable / a key uses a non-mappable form."""
    parts = combo.split(">")  # chord
    out_parts = []
    touched = False
    for part in parts:
        tokens = part.split("+")
        key = tokens[-1]
        # Mods only — skip
        if key.lower() in MODIFIER_TOKENS:
            return None
        # Translate only single-char ASCII keys
        if len(key) == 1 and key in xlate:
            tokens[-1] = xlate[key]
            touched = True
        elif len(key) == 1 and key.isascii() and key.isalnum():
            # ascii char NOT in mapping (e.g. digit) — keep as-is
            pass
        else:
            # named key (f1, escape, equal, kp_add, etc.) — keep as-is
            pass
        out_parts.append("+".join(tokens))
    if not touched:
        return None
    return ">".join(out_parts)


def collect_existing(sources: list[Path]) -> set[str]:
    """Set of canonicalized `map <combo>` first-tokens already present."""
    seen = set()
    for s in sources:
        if not s.exists():
            continue
        for ln in s.read_text().splitlines():
            ln = ln.strip()
            if ln.startswith("#"):
                continue
            m = MAP_RE.match(ln)
            if m:
                seen.add(m.group(1))
    return seen


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true")
    ap.add_argument("--sources", nargs="*", default=DEFAULT_SOURCES)
    args = ap.parse_args()

    xlate = load_xlate()
    sources = [KITTY_DIR / s for s in args.sources]
    existing = collect_existing(sources)

    out_lines = [
        "# Auto-generated by ~/.config/keymaps/kitty-gen.py — do not edit.",
        f"# Mapping: {MAP_PATH}",
        f"# Sources: {', '.join(args.sources)}",
        "",
    ]
    added = 0
    skipped_dup = 0
    # combo → index in out_lines; last definition wins on duplicates
    seen_in_out: dict[str, int] = {}

    # ── terminal ctrl+key signals (send_text twins) ──
    # Ctrl+C in raw mode sends \x03; same byte works for every app.
    CTRL_SIGNALS: list[tuple[str, str]] = [
        ("ctrl+c", r"\x03"),  # SIGINT / interrupt
        ("ctrl+d", r"\x04"),  # EOF / logout
        ("ctrl+z", r"\x1a"),  # SIGTSTP / suspend
    ]
    out_lines.append("# === terminal ctrl+key signals ===")
    for combo, byte_seq in CTRL_SIGNALS:
        ru_combo = translate_combo(combo, xlate)
        if ru_combo is None or ru_combo == combo or ru_combo in existing:
            continue
        out_lines.append(f"map {ru_combo} send_text all {byte_seq}")
        seen_in_out[ru_combo] = len(out_lines) - 1
        added += 1
    out_lines.append("")

    # ── kitty built-in defaults (not in any config file) ──
    out_lines.append("# === kitty built-in defaults ===")
    for combo, action in KITTY_DEFAULTS:
        ru_combo = translate_combo(combo, xlate)
        if ru_combo is None or ru_combo == combo:
            continue
        if ru_combo in existing:
            skipped_dup += 1
            continue
        out_lines.append(f"map {ru_combo} {action}")
        seen_in_out[ru_combo] = len(out_lines) - 1
        added += 1
    out_lines.append("")

    # ── user config files ──
    for src in sources:
        if not src.exists():
            continue
        out_lines.append(f"# === from {src.name} ===")
        for ln in src.read_text().splitlines():
            m = MAP_RE.match(ln)
            if not m:
                continue
            combo, action = m.group(1), m.group(2)
            ru_combo = translate_combo(combo, xlate)
            if ru_combo is None or ru_combo == combo:
                continue
            if ru_combo in existing:
                skipped_dup += 1
                continue
            if ru_combo in seen_in_out:
                # Last definition wins — replace previous output line
                idx = seen_in_out[ru_combo]
                out_lines[idx] = (
                    f"map {ru_combo} {action}" if action
                    else f"map {ru_combo}"
                )
                continue
            if action:
                out_lines.append(f"map {ru_combo} {action}")
            else:
                # `map <combo>` alone (unbinds) — preserve form
                out_lines.append(f"map {ru_combo}")
            seen_in_out[ru_combo] = len(out_lines) - 1
            added += 1
        out_lines.append("")

    out_path = KITTY_DIR / OUT_NAME
    out_path.write_text("\n".join(out_lines) + "\n")
    print(f"✔ wrote {out_path}")
    print(f"  added {added} twin map directives ({skipped_dup} skipped as already-bound)")

    if args.apply:
        kitty_conf = KITTY_DIR / "kitty.conf"
        text = kitty_conf.read_text()
        include_line = f"include {OUT_NAME}"
        if include_line not in text:
            with kitty_conf.open("a") as f:
                if not text.endswith("\n"):
                    f.write("\n")
                f.write(f"\n# russian-layout twins (auto-generated)\n{include_line}\n")
            print(f"✔ appended `{include_line}` to {kitty_conf}")
        else:
            print(f"  include already present in {kitty_conf.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
